Optimization: Collect output in parallel in `TestRunner::run_test_inner`
nextest-rs/nextest pull request #559
Opened 2022-10-04 11:29 UTC by NobodyXu

* Add new dep tokio-util v0.7.4 to nextest-runner
* Create new type `ReadTask` for spawning the read tasks and handles the cancellation.

This moves collection of output to a separate tokio task instead of doing it in the `tokio::select!` loop, which can be the bottleneck since `tokio::select!` is quite complex.

This also simplify the implementation by replacing the second `tokio::select!` loop with a spawned job.

All of the `*_done` boolean flags is also removed.

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

2022-10-04 20:10 UTC, sunshowers commented
Thank you so much for your contribution!

After looking at it in detail over a few hours, I'm respectfully going to have to unfortunately decline most of it. I really appreciate the effort put in! However, in my performance profiling, reading from stdout/stderr has just never been the bottleneck compared to things like process spawning. This adds a couple extra deps and a significant amount of complexity to a process that's pretty straightforward today, even if it isn't optimal.

The removal of `BufReader` is an easy change, though, and if you want to create a PR with that change I'd be happy to land it.

Thanks again!

2022-10-04 20:53 UTC, sunshowers requested changes
Requesting changes as mentioned in previous post.

2022-10-05 00:54 UTC, NobodyXu commented
Got it, I will open another PR that removes `BufReader`.

2022-10-05 00:54 UTC, closed without merging

2022-10-05 01:10 UTC, NobodyXu commented
> The removal of BufReader is an easy change, though, and if you want to create a PR with that change I'd be happy to land it.

I've opened a new PR #560